// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vnmac_elearning.Api.Infrastructure;

#nullable disable

namespace vnmac_elearning.Api.Infrastructure.Migrations
{
    [DbContext(typeof(TrainingDbContext))]
    [Migration("20260414084742_EnforceRelationalLearningSchema")]
    partial class EnforceRelationalLearningSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("vnmac_elearning.Api.Domain.Certificate", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CertificateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("IssuedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("CertificateId")
                        .IsUnique()
                        .HasFilter("[CertificateId] IS NOT NULL");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.CourseSection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Order")
                        .IsUnique();

                    b.ToTable("CourseSections");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.InteractionAttempt", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "LessonId", "AttemptNumber");

                    b.HasIndex("LessonId");

                    b.ToTable("InteractionAttempts");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.InteractionAttemptResult", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("QuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Correct")
                        .HasColumnType("bit");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LessonId", "AttemptNumber", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("InteractionAttemptResults");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.Lesson", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StatusLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoContent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId", "CourseId");

                    b.HasIndex("SectionId", "Order")
                        .IsUnique();

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.LessonAssessment", b =>
                {
                    b.Property<string>("LessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PassScore")
                        .HasColumnType("int");

                    b.Property<bool>("RandomizeOptionOrder")
                        .HasColumnType("bit");

                    b.Property<bool>("RandomizeQuestionOrder")
                        .HasColumnType("bit");

                    b.Property<string>("RetryHint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonId");

                    b.ToTable("LessonAssessments");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.LessonQuestion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MediaTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScenarioContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScenarioTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId", "Order")
                        .IsUnique();

                    b.ToTable("LessonQuestions");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.LessonQuestionDragItem", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("QuestionId", "Code");

                    b.HasIndex("QuestionId", "Order")
                        .IsUnique();

                    b.ToTable("LessonQuestionDragItems");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.LessonQuestionDragPair", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DragItemCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DragTargetCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("QuestionId", "DragItemCode", "DragTargetCode");

                    b.HasIndex("QuestionId", "DragTargetCode");

                    b.ToTable("LessonQuestionDragPairs");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.LessonQuestionDragTarget", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("QuestionId", "Code");

                    b.HasIndex("QuestionId", "Order")
                        .IsUnique();

                    b.ToTable("LessonQuestionDragTargets");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.LessonQuestionHotspotTarget", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<double>("Radius")
                        .HasColumnType("float");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.HasKey("QuestionId", "Code");

                    b.HasIndex("QuestionId", "Order")
                        .IsUnique();

                    b.ToTable("LessonQuestionHotspotTargets");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.LessonQuestionOption", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("QuestionId", "Code");

                    b.HasIndex("QuestionId", "Order")
                        .IsUnique();

                    b.ToTable("LessonQuestionOptions");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.ProgressTracking", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("CompletionTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("InteractionAttempts")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WatchPercent")
                        .HasColumnType("int");

                    b.Property<int>("WatchTimeMinutes")
                        .HasColumnType("int");

                    b.HasKey("UserId", "LessonId");

                    b.HasIndex("LessonId");

                    b.ToTable("ProgressTrackings");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.QuizAttempt", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("UserId", "LessonId", "AttemptNumber");

                    b.HasIndex("LessonId");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.QuizAttemptWrongQuestion", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("QuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "LessonId", "AttemptNumber", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuizAttemptWrongQuestions");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.QuizResult", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("UserId", "LessonId");

                    b.HasIndex("LessonId");

                    b.ToTable("QuizResults");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastLogin")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] <> ''");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.Certificate", b =>
                {
                    b.HasOne("vnmac_elearning.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.CourseSection", b =>
                {
                    b.HasOne("vnmac_elearning.Api.Domain.Course", null)
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.InteractionAttempt", b =>
                {
                    b.HasOne("vnmac_elearning.Api.Domain.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vnmac_elearning.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.InteractionAttemptResult", b =>
                {
                    b.HasOne("vnmac_elearning.Api.Domain.LessonQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("vnmac_elearning.Api.Domain.InteractionAttempt", null)
                        .WithMany("QuestionResults")
                        .HasForeignKey("UserId", "LessonId", "AttemptNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.Lesson", b =>
                {
                    b.HasOne("vnmac_elearning.Api.Domain.CourseSection", null)
                        .WithMany("Lessons")
                        .HasForeignKey("SectionId", "CourseId")
                        .HasPrincipalKey("Id", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.LessonAssessment", b =>
                {
                    b.HasOne("vnmac_elearning.Api.Domain.Lesson", null)
                        .WithOne("Assessment")
                        .HasForeignKey("vnmac_elearning.Api.Domain.LessonAssessment", "LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.LessonQuestion", b =>
                {
                    b.HasOne("vnmac_elearning.Api.Domain.LessonAssessment", null)
                        .WithMany("Questions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.LessonQuestionDragItem", b =>
                {
                    b.HasOne("vnmac_elearning.Api.Domain.LessonQuestion", null)
                        .WithMany("DragItems")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.LessonQuestionDragPair", b =>
                {
                    b.HasOne("vnmac_elearning.Api.Domain.LessonQuestion", null)
                        .WithMany("CorrectPairs")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vnmac_elearning.Api.Domain.LessonQuestionDragItem", null)
                        .WithMany()
                        .HasForeignKey("QuestionId", "DragItemCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("vnmac_elearning.Api.Domain.LessonQuestionDragTarget", null)
                        .WithMany()
                        .HasForeignKey("QuestionId", "DragTargetCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.LessonQuestionDragTarget", b =>
                {
                    b.HasOne("vnmac_elearning.Api.Domain.LessonQuestion", null)
                        .WithMany("DragTargets")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.LessonQuestionHotspotTarget", b =>
                {
                    b.HasOne("vnmac_elearning.Api.Domain.LessonQuestion", null)
                        .WithMany("HotspotTargets")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.LessonQuestionOption", b =>
                {
                    b.HasOne("vnmac_elearning.Api.Domain.LessonQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.ProgressTracking", b =>
                {
                    b.HasOne("vnmac_elearning.Api.Domain.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vnmac_elearning.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.QuizAttempt", b =>
                {
                    b.HasOne("vnmac_elearning.Api.Domain.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vnmac_elearning.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.QuizAttemptWrongQuestion", b =>
                {
                    b.HasOne("vnmac_elearning.Api.Domain.LessonQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("vnmac_elearning.Api.Domain.QuizAttempt", null)
                        .WithMany("WrongQuestions")
                        .HasForeignKey("UserId", "LessonId", "AttemptNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.QuizResult", b =>
                {
                    b.HasOne("vnmac_elearning.Api.Domain.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vnmac_elearning.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.RefreshToken", b =>
                {
                    b.HasOne("vnmac_elearning.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.CourseSection", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.InteractionAttempt", b =>
                {
                    b.Navigation("QuestionResults");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.Lesson", b =>
                {
                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.LessonAssessment", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.LessonQuestion", b =>
                {
                    b.Navigation("CorrectPairs");

                    b.Navigation("DragItems");

                    b.Navigation("DragTargets");

                    b.Navigation("HotspotTargets");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("vnmac_elearning.Api.Domain.QuizAttempt", b =>
                {
                    b.Navigation("WrongQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
