import type { LessonContentStep } from "@/shared/types/api";
import { emptyStep } from "./contentTypes";

export const officialStepBlueprints: LessonContentStep[] = [
  {
    ...emptyStep,
    key: "intro",
    order: 1,
    label: "Giới thiệu",
    screenType: "Giới thiệu bài học và mục tiêu",
    description: "Mở đầu bài học, giới thiệu bối cảnh, mục tiêu và thông điệp chính.",
    progressPercent: 0,
    title: "Nhận diện vật nổ",
    subtitle: "GIỚI THIỆU BÀI HỌC",
    body: "Trong cuộc sống hằng ngày, chúng ta có thể gặp những vật lạ nguy hiểm. Bài học này giúp bạn nhận biết và xử lý an toàn.",
    primaryActionLabel: "Bắt đầu học",
    mediaType: "image",
    mediaAlt: "Minh họa khu vực nguy hiểm có bom mìn",
    explanationTitle: "Mục tiêu bài học",
    explanation: "Giới thiệu mục tiêu, bối cảnh và thông điệp an toàn chính của bài học.",
    points: ["Nhận biết một số loại vật nổ thường gặp", "Phân biệt vật nguy hiểm - không chắc - an toàn", "Biết cách xử lý đúng khi gặp vật lạ"],
    tips: ["Nhận biết - Tránh xa - Báo ngay"],
  },
  {
    ...emptyStep,
    key: "video",
    order: 2,
    label: "Video",
    screenType: "Nội dung chính bằng video hoặc slide",
    description: "Trình bày nội dung chính bằng hình ảnh trực quan và ngôn ngữ đơn giản.",
    progressPercent: 25,
    title: "Xem video",
    subtitle: "Nội dung chính",
    body: "Video hoặc slide trình bày nội dung chính bằng hình ảnh trực quan và ngôn ngữ đơn giản.",
    alertText: "Hãy luôn cảnh giác! Khi không chắc chắn, hãy coi là nguy hiểm.",
    primaryActionLabel: "Tiếp tục",
    mediaType: "video",
    mediaAlt: "Video bài học",
    explanationTitle: "Nội dung chính",
    explanation: "Tóm tắt các ý chính xuất hiện bên phải video để người học dễ theo dõi.",
    points: ["Vật nổ còn sót lại từ chiến tranh", "Có thể xuất hiện ở nhiều địa điểm khác nhau", "Nhiều vật bị gỉ sét, vỡ nát, khó nhận biết", "Nhận diện đúng và xử lý an toàn", "Bảo vệ bản thân và cộng đồng"],
    tips: ["Nhận biết - Tránh xa - Báo ngay"],
  },
  {
    ...emptyStep,
    key: "activity",
    order: 3,
    label: "Kéo thả",
    screenType: "Hoạt động nhận dạng hoặc thực hành tương tác",
    description: "Người học thực hành phân biệt hành vi đúng - sai hoặc xử lý tình huống.",
    progressPercent: 70,
    title: "Phân loại",
    subtitle: "Hãy kéo từng vật vào nhóm phù hợp.",
    instruction: "Nhấn giữ chuột vào vật, kéo và thả vào nhóm phù hợp. Phân loại đúng tất cả để tiếp tục.",
    alertText: "Khi không chắc chắn -> coi là nguy hiểm.",
    primaryActionLabel: "Kiểm tra",
    secondaryActionLabel: "Tiếp tục",
    mediaType: "image",
    explanationTitle: "Mẹo nhớ",
    explanation: "Không chạm vào vật lạ, tránh xa khi phát hiện và báo ngay cho người có trách nhiệm.",
    targets: ["Nguy hiểm", "Không chắc", "An toàn"],
    items: ["Bom phá", "Mìn chống tăng", "Lựu đạn", "Đá", "Lon nước", "Đạn cối", "Chai nhựa", "Vật lạ gỉ sét"],
    dragQuestions: [
      {
        id: "danger",
        order: 1,
        prompt: "Nguy hiểm",
        description: "Vật nổ chắc chắn, rất nguy hiểm",
        tone: "red",
        imageUrl: "",
        imageAlt: "",
        answers: [
          { id: "bom-pha", order: 1, label: "Bom phá", description: "", imageUrl: "", imageAlt: "", feedback: "" },
          { id: "min-chong-tang", order: 2, label: "Mìn chống tăng", description: "", imageUrl: "", imageAlt: "", feedback: "" },
          { id: "luu-dan", order: 3, label: "Lựu đạn", description: "", imageUrl: "", imageAlt: "", feedback: "" },
          { id: "dan-coi", order: 4, label: "Đạn cối", description: "", imageUrl: "", imageAlt: "", feedback: "" },
        ],
      },
      {
        id: "uncertain",
        order: 2,
        prompt: "Không chắc",
        description: "Không chắc là vật nổ, cần thận trọng",
        tone: "amber",
        imageUrl: "",
        imageAlt: "",
        answers: [{ id: "vat-la-gi-set", order: 1, label: "Vật lạ gỉ sét", description: "", imageUrl: "", imageAlt: "", feedback: "" }],
      },
      {
        id: "safe",
        order: 3,
        prompt: "An toàn",
        description: "Vật dụng thông thường, an toàn",
        tone: "green",
        imageUrl: "",
        imageAlt: "",
        answers: [
          { id: "da", order: 1, label: "Đá", description: "", imageUrl: "", imageAlt: "", feedback: "" },
          { id: "lon-nuoc", order: 2, label: "Lon nước", description: "", imageUrl: "", imageAlt: "", feedback: "" },
          { id: "chai-nhua", order: 3, label: "Chai nhựa", description: "", imageUrl: "", imageAlt: "", feedback: "" },
        ],
      },
    ],
    tips: ["Không chạm vào vật lạ", "Tránh xa khi phát hiện", "Báo ngay cho người có trách nhiệm", "Bảo vệ bản thân và cộng đồng"],
  },
  {
    ...emptyStep,
    key: "reinforce",
    order: 4,
    label: "Củng cố",
    screenType: "Phản hồi và củng cố nội dung",
    description: "Tóm tắt thông điệp quan trọng, phản hồi ngay để người học ghi nhớ.",
    progressPercent: 70,
    title: "Củng cố kiến thức",
    subtitle: "Hãy ghi nhớ những nguyên tắc an toàn quan trọng",
    body: "Ghi nhớ quan trọng",
    alertText: "Khi không chắc chắn -> LUÔN coi là nguy hiểm",
    mediaType: "image",
    mediaAlt: "Minh họa cán bộ cảnh báo khu vực nguy hiểm",
    explanationTitle: "Mẹo nhớ",
    explanation: "Tổng hợp các nguyên tắc người học cần ghi nhớ trước khi làm kiểm tra.",
    points: ["Không chạm vào vật lạ", "Tránh xa ngay lập tức", "Báo cho người có trách nhiệm"],
    tips: ["Không chạm vào vật lạ", "Tránh xa ngay lập tức", "Báo ngay cho người có trách nhiệm", "Bảo vệ bản thân và cộng đồng"],
    feedback: "Bạn đã hiểu cách nhận diện vật nguy hiểm. Hãy tiếp tục để kiểm tra lại kiến thức.",
  },
  {
    ...emptyStep,
    key: "check",
    order: 5,
    label: "Kiểm tra",
    screenType: "Bài kiểm tra cuối bài",
    description: "Mô tả phần kiểm tra cuối bài trong cấu trúc nội dung; câu hỏi chính thức từng bài sẽ bổ sung sau.",
    progressPercent: 90,
    title: "Kiểm tra cuối bài",
    subtitle: "Chọn câu trả lời đúng nhất.",
    body: "Bạn thấy một vật kim loại lạ trong ruộng, bạn nên làm gì?",
    alertText: "Đạt 100% để hoàn thành bài học",
    mediaType: "image",
    mediaAlt: "Minh họa câu hỏi kiểm tra cuối bài",
    explanationTitle: "Thông tin bài kiểm tra",
    explanation: "Phần này chỉ là cấu trúc hiển thị cho kiểm tra cuối bài. Bộ câu hỏi chính thức từng bài sẽ bổ sung sau.",
    options: ["Nhặt lên xem", "Mang về nhà", "Tránh xa và báo cho người lớn / người có trách nhiệm"],
    feedback: "Chính xác! Đây là hành vi an toàn.",
  },
  {
    ...emptyStep,
    key: "complete",
    order: 6,
    label: "Hoàn thành",
    screenType: "Màn hình hoàn thành",
    description: "Xác nhận hoàn thành bài học và hướng người học sang bước tiếp theo.",
    progressPercent: 100,
    title: "Hoàn thành",
    subtitle: "Chúc mừng!",
    body: "Bạn đã hoàn thành bài học.",
    primaryActionLabel: "Sang bài tiếp theo",
    secondaryActionLabel: "Xem lại nội dung",
    mediaType: "image",
    mediaAlt: "Minh họa hoàn thành bài học",
    explanationTitle: "Kết quả bài học",
    explanation: "Hiển thị điểm, trạng thái đạt yêu cầu và tiến độ chủ đề.",
    points: ["Bạn đã đạt 100% điểm trong bài kiểm tra", "Bạn đã nắm vững kiến thức nhận diện vật nguy hiểm"],
    tips: ["Học lại bài học", "Xem lại nội dung", "Sang bài tiếp theo"],
  },
];

export const blueprintByKey = new Map(officialStepBlueprints.map((step) => [step.key, step]));
